#!/bin/bash

#############################################################
# ZYB TX SERVICE 
#############################################################

SERVICE_NAME="zybfireGPIO"
EXECUTABLE="zyb-fireGPIO"
USER=$(whoami)
CWD=$(pwd)

SERVICE_FILE="/etc/systemd/system/$SERVICE_NAME.service"

echo "Creating systemd service file at $SERVICE_FILE..."

sudo bash -c "cat > $SERVICE_FILE" <<EOL
[Unit]
After=network-online.target multi-user.target
Wants=network-online.target


[Service]
WorkingDirectory=$CWD
ExecStartPre=/bin/sleep 10
ExecStart=$CWD/$EXECUTABLE
Restart=always
RestartSec=10
User=$USER
Group=audio
SupplementaryGroups=audio
StandardOutput=journal
StandardError=journal
Environment="PULSE_SERVER=unix:/run/user/1000/pulse/native"
Environment="DISPLAY=:0"
Environment="XDG_RUNTIME_DIR=/run/user/1000"

[Install]
WantedBy=multi-user.target
[Unit]
Description=zybtxd Service
After=network-online.target
Wants=network-online.target
EOL

echo "Setting executable permissions..."
chmod +x "$CWD/$EXECUTABLE"

echo "Reloading systemd and enabling service..."
sudo systemctl daemon-reload
sudo systemctl start $SERVICE_NAME.service
sudo systemctl enable $SERVICE_NAME.service

echo "Checking service status..."
sudo systemctl status $SERVICE_NAME.service


echo "Done! You can view logs using: journalctl -u $SERVICE_NAME.service -f"
