#!/usr/bin/python3

import os
import threading
import RPi.GPIO as GPIO
import time

BCM_INPUT_PIN = 10

GPIO.setmode(GPIO.BCM)
GPIO.setup(BCM_INPUT_PIN, GPIO.IN)  # GPIO10, which is Pin 19 on a pi 3b+ board

def run_wolf():
    os.system('direwolf')

def capture():
    os.system('./run')

def listen_to_gpio():
    try:
        while True:
            if GPIO.input(10) == GPIO.HIGH:
                print("GPIO10 is HIGH, starting capture and direwolf...")
                capture_thread = threading.Thread(target=capture)
                wolf_thread = threading.Thread(target=run_wolf)

                wolf_thread.start()
                capture_thread.start()
                
                capture_thread.join()
                print("Capture complete")
                wolf_thread.join()
                print("Direwolf process complete")

            time.sleep(0.1)
    except KeyboardInterrupt:
        GPIO.cleanup()
        print("Clean exit")

if __name__ == "__main__":
    listen_to_gpio()
