#!/usr/bin/python3

import os
import socket
import threading


BUFFER_LEN = 1024
HOST = '127.0.0.1'
PORT = 7887

def run_wolf():
    os.system('direwolf')

def capture():
    os.system('./run')

def start_server():
    addr = (HOST, PORT)
    serv_sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    
    try:
        serv_sock.bind(addr)
        serv_sock.listen(1)
    except Exception as e:
        print(e)
        serv_sock.close()
        return
    
    while True:
        print("accepting connections..")
        try:
            client_sock, client_addr = serv_sock.accept()
            print(f"Connection from {client_addr}")

            data = client_sock.recv(BUFFER_LEN).decode('utf-8').strip()
            if data == "capture picture now":
                capture_thread = threading.Thread(target=capture)
                wolf_thread = threading.Thread(target=run_wolf)
                
                wolf_thread.start()
                capture_thread.start()

                print("threads fired")               
                
                wolf_thread.join()
                capture_thread.join()

                print("threads joined")
            elif data == "exit": break
            else: 
                print("bad frame")
                response = "invalid event"
                client_sock.send(response.encode('utf-8'))
            client_sock.close()

        except Exception as e:
            print(e)
            serv_sock.close()
            break

    wolf_thread.join()
    capture_thread.join()
    serv_sock.close()
    print("closed server")
    


if __name__ == "__main__":
	start_server()
