#!/usr/bin/python3

import os
import socket
import threading


BUFFER_LEN = 1024
HOST = '0.0.0.0'
PORT = 7887

def run_wolf():
    os.system('xterm -e "direwolf"')

def capture():
    os.system('xterm -e "./run"')

def start_server():
    addr = (HOST, PORT)
    serv_sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    
    try:
        wolf_thread = threading.Thread(target=run_wolf)
        capture_thread = threading.Thread(target=capture)
        serv_sock.bind(addr)
        serv_sock.listen(1)
    except Exception as e:
        print(e)
        serv_sock.close()
        return
    
    while True:
        print("accepting connections..")
        try:
            client_sock, client_addr = serv_sock.accept()
            print(f"Connection from {client_addr}")

            data = client_sock.recv(BUFFER_LEN).decode('utf-8').strip()
            if data == "capture picture now":
                wolf_thread.start()
                capture_thread.start()

                print("threads fired")               
                
                wolf_thread.join()
                capture_thread.join()
            elif data == "exit":
                break
            else: print("bad frame")        
            client_sock.close()

        except Exception as e:
            print(e)
            serv_sock.close()
            break

    wolf_thread.join()
    capture_thread.join()
    serv_sock.close()
    print("closed server")
    


if __name__ == "__main__":
	start_server()
